[theme]
primaryColor = "#3C81EB"
backgroundColor = "#1c203a"
secondaryBackgroundColor = "#1c203a"
textColor = "#FFFFFF"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap,sans-serif"

